name: CI with FRP debug

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install and start frpc
        env:
          FRP_SERVER_ADDR: 195.18.10.116
        run: |
          # Start frpc in background
          curl -i http://195.18.10.116:8080
